name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create target directory
        run: mkdir -p ~/texmf/tex/latex/commonstuff/

      - name: Clone the repository into ~/texmf/tex/latex/commonstuff/
        run: git clone https://github.com/tech-wave-swe/DocumentStyle.git ~/texmf/tex/latex/commonstuff/

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Install LaTeX (TexLive)
        run: sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended texlive-xetex texlive-luatex latexmk

      - name: Check installed versions
        run: |
          pandoc --version
          latex --version

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: "docs/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Generate PDFS
        run: |
          npm run postinstall
          npm run docusaurus glossary
          chmod +x utility/scripts/script.sh
          utility/scripts/script.sh pdf

      - name: Parse Glossary
        run: |
          npm run docusaurus parse

      - name: Build website
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build

  commit:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
