name: Test build

on:
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - "docs/**"
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "docs/**"
  workflow_dispatch:

jobs:
  test-deploy:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug
        run: |
          ls -la
          ls -la ${{ github.workspace }}
          git clean -fdx

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: ./package-lock.json
          node-version: "22.14.0"

      - name: Install dependencies
        run: |
          npm ci

      - name: Run Tests
        run: |
          npm run test:jest