name: Test build

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "docs/**"

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug
        run: ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull prebuilt Docker container
        run: |
          docker pull lucamonetti/tw-latex:latest

      - name: Run commands inside the Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/app \
            -e PR_REF=${{ github.ref }} \
            -e PR_SHA=${{ github.sha }} \
            lucamonetti/tw-latex:latest bash -c "
              ls -la
              cd docs
              npm ci
              mkdir static/pdfs
              npm run postinstall
              npm run docusaurus glossary
              chmod +x utility/scripts/script.sh
              utility/scripts/script.sh pdf
              npm run docusaurus parse
              npm run build
            "

      - name: List directory contents for debugging
        run: |
          ls -la
          ls -la build

      - name: Show PWD
        run: pwd
